apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-root
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mazin1hn/eks.git
    targetRevision: main
    path: argocd/apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      enabled: true 
      prune: true
      selfHeal: true
    syncOptions:
     - ServerSideApply=true 